name: 'salesanalysis'
version: '1.0.0'

profile: 'salesAnalysis'
model-paths: ["models"]

clean-targets:         
  - "target"
  - "dbt_packages"

models:
  salesAnalysis:
    example:
      +materialized: view
